pages:
  # It's not necessary to create a new file for each page and include it, you can simply
  # put its contents here, though multiple pages are easier to manage when separated
  !include: llms.yml
  !include: dev-blogs.yml
